name: DBT PR build

on:
  pull_request:

jobs:
  dbt:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install deps
        run: pip install dbt datafold-sdk

      - name: run seed
        run: dbt seed --full-refresh --profiles-dir ./
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_SCHEMA: BEERS_DEV

      - name: run dbt
        run: dbt run --profiles-dir ./
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_SCHEMA: BEERS_DEV

      - name: submit artifacts to datafold
        run: |
          set -ex
          export PR_SHA=$(git rev-list --no-merges -n 1 HEAD)
          datafold dbt upload --ci-config-id 19 --run-type=pull_request --target-folder ./target/ --commit-sha ${PR_SHA}
        env:
          DATAFOLD_APIKEY: ${{ secrets.DATAFOLD_APIKEY }}
